spring:
  mail:
    host: smtp.naver.com
    port: 587
    username: am030818@naver.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
      debug: true
  datasource:
    url: jdbc:mariadb://localhost:3306/secondserve
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: keypass

imp:
  code: imp85340474
  api:
    key: 7276428457236882
    secretkey: WUo76J6jqy8UhQeT7sBGfek2Asoo4d72g8QybVP9oPMdXQlSZ6zspLIb1DIZb6OTPf3Eje1KuZVtSqXp

  #jpa:
    #generate-ddl: true
    #show-sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.MariaDBDialect
  cache:
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m


server:
  port: 8080
  address: 0.0.0.0

jwt:
  issuer: am030818@naver.com
  secret: "jfsgkhdsjkweoiruwqejkrfbhnsadkjlfghbwerqewrsdfgdsfagbdf"
  access-expiration: 3600
  refresh-expiration: 8640

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
